### ISSUE TITLE
Primary Device Attribute of Sixel support : 4 

### ISSUE THREAD

**Issue by animalsThink** [odknt/st#1]
char *vtiden = "\033[?6c";  ---->  char *vtiden = "\033[?4;6c";

**Comment by pmp-p** [comment]
@animalsThink thanks, but what would it solve ? as you probably already know what it does : a bit of explanation would save people from searching.

it could also benefit disconnected forks of st such as https://github.com/charlesdaniels/st/issues

**Comment by animalsThink** [comment]
@pmp-p some apps check primary device attribute to know whether your terminal supports sixel.

**Comment by odknt** [comment]
@animalsThink That's new for me. Thanks.
